version: "3.4"
services:
  altv:
    image: daschaos/altv-csharp:stable
    restart: unless-stopped
    volumes:
      - data:/altv-persistend/
    ports:
      - "7788:7788"
      - "7788:7788/udp"
volumes:
  data:
